zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.10.0
  ports:
    - 2181:2181
    - 2888:2888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.10.0
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  image: eventuateio/eventuateio-local-mysql:0.10.0
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

query:
  image: networknt/eventuate-query:1.3.0
  ports:
    - "8091:8080"
  volumes:
    - ./docker/query/config:/config
    - ./docker/query/service:/service
  links:
    - mysql
    - kafka
    - zookeeper

command:
  image: networknt/eventuate-command:1.3.0
  ports:
    - "8092:8080"
  volumes:
    - ./docker/command/config:/config
    - ./docker/command/service:/service
  links:
    - mysql
    - kafka
    - zookeeper
